"""add import_logs table

Revision ID: 65ee3d5c9bc0
Revises: 
Create Date: 2026-07-03 18:32:41.439293
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '65ee3d5c9bc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title_name', sa.String(length=255), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_logs')
    # ### end Alembic commands ###
