"""migrate import_logs UUID to String

Revision ID: a2e610c2240c
Revises: 3aaff18e030f
Create Date: 2026-07-03 18:47:56.052831
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a2e610c2240c'
down_revision: Union[str, None] = '3aaff18e030f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE import_logs DROP CONSTRAINT IF EXISTS import_logs_user_id_fkey")
    op.alter_column('import_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               postgresql_using='id::varchar')
    op.alter_column('import_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False,
               postgresql_using='user_id::varchar')
    op.alter_column('import_logs', 'title_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=True,
               postgresql_using='title_id::varchar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_logs', 'title_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('import_logs', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('import_logs', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
